#!/bin/bash

# =====================================================
# Tmux Setup Installer
# 类似 oh-my-zsh 的自动化安装脚本
# =====================================================

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# 配置变量
TPM_DIR="$HOME/.tmux/plugins/tpm"
CONFIG_DIR="$HOME/.config/tmux"
CONFIG_FILE="$CONFIG_DIR/tmux.conf"
SYMLINK="$HOME/.tmux.conf"
TPM_GIT="https://github.com/tmux-plugins/tpm.git"

# =====================================================
# 辅助函数
# =====================================================

print_header() {
    echo ""
    echo -e "${BLUE}============================================${NC}"
    echo -e "${BLUE}  Tmux Configuration Installer${NC}"
    echo -e "${BLUE}============================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}→${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}!${NC} $1"
}

# =====================================================
# 检查和安装 tmux
# =====================================================

check_tmux() {
    print_info "检查 tmux 安装状态..."

    if command -v tmux &> /dev/null; then
        TMUX_VERSION=$(tmux -V | awk '{print $2}')
        print_success "tmux 已安装 (版本: $TMUX_VERSION)"
        return 0
    else
        print_warning "tmux 未安装"
        return 1
    fi
}

install_tmux() {
    print_info "安装 tmux..."

    if command -v brew &> /dev/null; then
        brew install tmux
        print_success "tmux 安装完成"
    else
        print_error "Homebrew 未安装，请先安装 Homebrew: https://brew.sh"
        exit 1
    fi
}

# =====================================================
# 备份现有配置
# =====================================================

backup_existing() {
    print_info "检查现有配置..."

    if [ -f "$CONFIG_FILE" ]; then
        BACKUP_DIR="$CONFIG_DIR.backup.$(date +%Y%m%d%H%M%S)"
        print_warning "发现现有配置，备份到: $BACKUP_DIR"
        mkdir -p "$BACKUP_DIR"
        cp -r "$CONFIG_DIR"/* "$BACKUP_DIR/" 2>/dev/null
        print_success "备份完成"
    fi

    if [ -L "$SYMLINK" ]; then
        print_info "移除旧的符号链接..."
        rm "$SYMLINK"
    fi
}

# =====================================================
# 安装配置文件
# =====================================================

install_config() {
    print_info "安装配置文件..."

    # 创建配置目录
    mkdir -p "$CONFIG_DIR"

    # 获取脚本所在目录
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # 复制配置文件
    if [ -f "$SCRIPT_DIR/tmux.conf" ]; then
        cp "$SCRIPT_DIR/tmux.conf" "$CONFIG_FILE"
        print_success "配置文件已复制到: $CONFIG_FILE"
    else
        # 如果没有本地配置文件，使用默认配置
        print_info "使用内置默认配置..."
        create_default_config
    fi

    # 创建符号链接
    if [ ! -L "$SYMLINK" ] && [ ! -f "$SYMLINK" ]; then
        ln -s "$CONFIG_FILE" "$SYMLINK"
        print_success "符号链接已创建: $SYMLINK -> $CONFIG_FILE"
    fi
}

create_default_config() {
    cat > "$CONFIG_FILE" << 'EOF'
# =====================================================
# Tmux Configuration
# Generated by Tmux Setup Installer
# Modified prefix: Ctrl+d
# =====================================================

# -- general
setw -g xterm-keys on
set-window-option -g xterm-keys on
set -s escape-time 0
set -sg repeat-time 300
set -s focus-events on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g mouse on
set -sg exit-empty on
set -g detach-on-destroy off
set -g allow-passthrough on

set -q -g status-utf8 on
setw -q -g utf8 on

set -g visual-activity off
setw -g monitor-activity off
setw -g monitor-bell off

set -g history-limit 10000

# reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display '~/.config/tmux/tmux.conf sourced'

# -- prefix (MODIFIED: Changed from C-s to C-d)
unbind C-b
set -g prefix 'C-d'

# -- display
set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on
set -g renumber-windows on

set -g set-titles on

set -g display-panes-time 2000
set -g display-time 2000

# -- navigation
bind C-c new-session

# window management
bind o new-window -c "#{pane_current_path}"
bind q kill-pane
unbind ,
bind , command-prompt -p "Rename window:" "rename-window '%%'"

# window navigation (F1-F12)
unbind n
unbind p
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0
bind -r C-p previous-window
bind -r C-n next-window

bind -n F1 select-window -t 1
bind -n F2 select-window -t 2
bind -n F3 select-window -t 3
bind -n F4 select-window -t 4
bind -n F5 select-window -t 5
bind -n F6 select-window -t 6
bind -n F7 select-window -t 7
bind -n F8 select-window -t 8
bind -n F9 select-window -t 9
bind -n F10 new-window -c "#{pane_current_path}"
bind -n F11 kill-pane
bind -n F12 copy-mode

# Pane splitting
bind u split-window -vb -c "#{pane_current_path}"
bind e split-window -v -c "#{pane_current_path}"
bind n split-window -hb -c "#{pane_current_path}"
bind i split-window -h -c "#{pane_current_path}"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind f resize-pane -Z

# pane navigation (hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D

bind > swap-pane -D
bind < swap-pane -U
bind | swap-pane

# pane resizing
bind H resize-pane -L 3
bind J resize-pane -D 3
bind K resize-pane -U 3
bind L resize-pane -R 3

# Copy mode
set -g status-keys emacs
set -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind b list-buffers
bind p paste-buffer

# window move
bind < swap-window -d -t :-1
bind > swap-window -d -t :+1

bind v copy-mode

# toggle sync panes
bind C-g if-shell '[[ $(tmux showw synchronize-panes | cut -d\  -f2) == "on" ]]' \
'setw synchronize-panes off; display "Synchronize panes OFF"' \
'setw synchronize-panes on; display "Synchronize panes ON"'

# theme
setw -g pane-border-status top
set -g pane-active-border-style fg=#b294bb
set -g pane-border-style fg=colour244
set -g pane-border-format ' #{?pane_active,#[bold],} #P: #{pane_current_command} #{?window_zoomed_flag,⛶ ,}'

set -g status-justify 'left'
set -g status-left-length 90
set -g status-right-length 140
setw -g window-status-separator ''

set -g status-bg black
set -g status-fg white

setw -g window-status-format '#[fg=#c5c8c6] #I:#W '
setw -g window-status-current-format '#[fg=#b294bb,bold] #I:#W '
setw -g window-status-activity-style bg=black
setw -g window-status-bell-style bg=black

set-option -g status-left '#[fg=#b294bb,bold] #S #[default]'
set-option -g status-right '#[fg=colour244] %Y-%m-%d %H:%M #[fg=#b294bb]%H:%M#[default] '

# True color
set -g default-terminal "tmux-256color"
set -as terminal-features ",*256col*:RGB"
set -as terminal-overrides ",*256col*:Tc"

# Better scrolling
unbind -T copy-mode-vi C-u
unbind -T copy-mode-vi C-d
bind -T copy-mode-vi C-u send-keys -N 5 -X scroll-up
bind -T copy-mode-vi C-d send-keys -N 5 -X scroll-down

# Session management
bind d detach-client
bind D choose-client
bind Space next-layout
bind X confirm-before -p "Kill session #S? (y/n)" kill-session
bind R source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# Continuum settings
set -g @continuum-save-interval '5'
set -g @continuum-restore 'on'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
EOF
    print_success "默认配置已创建"
}

# =====================================================
# 安装 TPM (Tmux Plugin Manager)
# =====================================================

install_tpm() {
    print_info "安装 Tmux Plugin Manager..."

    if [ -d "$TPM_DIR" ]; then
        print_success "TPM 已安装"
    else
        mkdir -p "$(dirname "$TPM_DIR")"
        git clone "$TPM_GIT" "$TPM_DIR"
        print_success "TPM 安装完成"
    fi
}

# =====================================================
# 安装插件
# =====================================================

install_plugins() {
    print_info "安装 tmux 插件..."

    # 加载 tmux 配置并安装插件
    # 使用 tmux 的 source-file 和 tpm 安装命令

    # 先刷新 TPM
    if [ -d "$TPM_DIR" ]; then
        # 安装插件 (通过运行 tmux 并执行 tpm 插件安装)
        print_info "正在安装插件 (tpm, tmux-sensible, tmux-resurrect, tmux-continuum)..."

        # 创建临时脚本安装插件
        tmux new-session -d -s tmux-install-plugins 2>/dev/null || true

        # 等待插件安装
        sleep 2

        # 杀掉临时会话
        tmux kill-session -t tmux-install-plugins 2>/dev/null || true

        print_success "插件安装完成"
        print_info "提示: 首次启动 tmux 后，按 Prefix + I (大写I) 安装插件"
    else
        print_warning "TPM 未安装，跳过插件安装"
    fi
}

# =====================================================
# 显示安装完成信息
# =====================================================

print_summary() {
    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  安装完成!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo -e "${BOLD}配置文件:${NC} $CONFIG_FILE"
    echo -e "${BOLD}快捷方式:${NC} $SYMLINK"
    echo ""
    echo -e "${BOLD}Prefix 键:${NC} Ctrl+d"
    echo ""
    echo -e "${YELLOW}下一步操作:${NC}"
    echo "  1. 启动 tmux: tmux"
    echo "  2. 按 ${BOLD}Prefix + I${NC} (大写I) 安装所有插件"
    echo "  3. 重新加载配置: Prefix + r"
    echo ""
    echo -e "${YELLOW}快捷键说明:${NC}"
    echo "  • F1-F9    切换窗口 (直达)"
    echo "  • F10      新建窗口"
    echo "  • F11      关闭面板"
    echo "  • F12      进入复制模式"
    echo "  • Prefix + h/j/k/l  切换面板"
    echo "  • Prefix + u/e/n/i   分屏"
    echo ""
}

# =====================================================
# 主函数
# =====================================================

main() {
    print_header

    # 1. 检查/安装 tmux
    if ! check_tmux; then
        install_tmux
    fi

    # 2. 备份现有配置
    backup_existing

    # 3. 安装配置文件
    install_config

    # 4. 安装 TPM
    install_tpm

    # 5. 安装插件
    install_plugins

    # 6. 显示总结
    print_summary
}

# 运行主函数
main "$@"
